name: RT
on: [push]
jobs:
  my-job:
    name: Run MATLAB Script
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Open MATLAB
        if: runner.os == 'Windows'
        run: echo "C:\Program Files\MATLAB\R2023a\bin"
      - name: Run script
        uses: matlab-actions/run-command@v2
        with:
          command: test
